### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by gvpatel** [forcedotcom/Salesforce-CDP-jdbc#23]
Hello -  Which OAuth Authorization Flows we need to use for this driver?

web server or JWT?

Also, what is coreToken?

 properties.put("coreToken", <Core oAuth token>);
 properties.put("refreshToken", <Refresh Token>);

**Comment by g1-pai** [comment]
We can use both oAuth flow as well as User name password flow for now. U can setup connected app as mentioned in https://extensiongallery.tableau.com/connectors/270?version=2021.1&per-page=200
