### ISSUE TITLE
Token exchange error on DBeaver

### ISSUE THREAD

**Issue by kamransh** [forcedotcom/Salesforce-CDP-jdbc#28]
Hi,
I get a _**Token Exchange Failed**_ error when running a query. It's connecting to CDP using the instance URL but the execution fails. Have you seen this before?

screenshot attached
Thanks
<img width="418" alt="2021-06-17_12-39-27" src="https://user-images.githubusercontent.com/7414464/122390456-ebd43200-cf69-11eb-9b14-f5826b627bb7.png">

**Comment by g1-pai** [comment]
Could you please check if you have imported the QS driver to Dbeaver.

**Comment by kevinquillen** [comment]
This is still an issue.
